[global]
address = "0.0.0.0"
port = 8000
# workers = [number_of_cpus * 2]
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[global.databases.splat_challenges]
url = "db/splat_challenges.db"
